name: build+test

on: push

env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get identifier for submodules
        id: smid
        run: |
          echo "::set-output name=id::$(git submodule status | cut -c 2-9 | tr '\n' '-' )"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          context: .
          target: mlirdb
          build-args: |
            buildImage=ghcr.io/jungmair/mlirdb-buildimg:${{ steps.smid.outputs.id }}
          push: true
          tags: ghcr.io/jungmair/mlirdb:${{ steps.smid.outputs.sha_short }}