name: build+test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get identifier for submodules
        id: smid
        run: |
          echo "::set-output name=id::$(git submodule status | cut -c 2-9 | tr '\n' '-' )"
      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          context: .
          tags: mlirdb:latest
          outputs: type=docker,dest=/tmp/builtimage.tar
          target: mlirdb
          build-args: |
            buildImage=ghcr.io/jungmair/mlirdb-buildimg:${{ steps.smid.outputs.id }}
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: builtimage
          path: /tmp/builtimage.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: builtimage
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/builtimage.tar
          docker image ls -a