name: build+test

on: push

jobs:
  build-arrow:
    runs-on: ubuntu-latest
    container: ghcr.io/jungmair/mlirdb:latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: ls /