name: build+test

on: push

env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get identifier for submodules
        id: smid
        run: |
          echo "::set-output name=id::$(git submodule status | cut -c 2-9 | tr '\n' '-' )"
      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          context: .
          target: mlirdb
          build-args: |
            buildImage=ghcr.io/jungmair/mlirdb-buildimg:${{ steps.smid.outputs.id }}
          push: true
          tags: ghcr.io/jungmair/mlirdb:${{ github.sha }}
  filecheck-tests:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/jungmair/mlirdb:${{ github.sha }}
    steps:
      - name: Run Test
        run: |
          cd /repo
          export LD_LIBRARY_PATH=/build/arrow/install/lib && /build/llvm/bin/llvm-lit -v /build/mlirdb/test/lit
  sql-tests:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/jungmair/mlirdb:${{ github.sha }}
    steps:
      - name: Run Test
        run: |
          cd /repo
          python3 /repo/tools/scripts/sql-roundtrip-test.py /build/mlirdb
  sqlite-tests:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/jungmair/mlirdb:${{ github.sha }}
    steps:
      - name: Run Test
        run: |
          cd /repo
          /build/mlirdb/sqlite-tester test/sqlite/select1.test
          /build/mlirdb/sqlite-tester test/sqlite/select2.test
          /build/mlirdb/sqlite-tester test/sqlite/select3.test
          /build/mlirdb/sqlite-tester test/sqlite/select4.test
          /build/mlirdb/sqlite-tester test/sqlite/select5.test
          /build/mlirdb/sqlite-tester test/sqlite/groupby.test
          /build/mlirdb/sqlite-tester test/sqlite/join.test
          /build/mlirdb/sqlite-tester test/sqlite/unnesting.test

  lint:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/jungmair/mlirdb:${{ github.sha }}
    steps:
      - name: Run Test
        run: |
          cd /repo
          python3 /repo/tools/scripts/run-clang-tidy.py -p /build/mlirdb -quiet  -exclude="arrow|vendored" -header-filter="$PWD/include/.*"  -clang-tidy-binary=/build/llvm/bin/clang-tidy